name: Django CI # Имя рабочего процесса, отображается в разделе Actions на GitHub

on: # Определяет, когда рабочий процесс должен быть запущен
  push: # Запускает рабочий процесс на каждый push
    branches: [ "main" ] # Указывает, что рабочий процесс запускается при пуше в ветку "main"
  pull_request: # Запускает рабочий процесс на каждый pull request
    branches: [ "main" ] # Указывает, что рабочий процесс запускается при создании pull request в ветку "main"

jobs: # Определяет задания, которые будут выполнены в рамках рабочего процесса
  build: # Имя задания

    runs-on: ubuntu-latest # Указывает, что задание будет выполняться на виртуальной машине с последней версией Ubuntu

    strategy: # Стратегия выполнения задания
      max-parallel: 4 # Максимальное количество заданий, выполняемых параллельно
      matrix: # Матрица стратегии для запуска заданий с различными версиями Python
        python-version: [3.9] # Список версий Python, для которых будет выполняться задание

    steps: # Шаги, которые необходимо выполнить в рамках задания
    - uses: actions/checkout@v3 # Использует действие checkout для клонирования репозитория
    - name: Set up Python ${{ matrix.python-version }} # Устанавливает версию Python в соответствии с матрицей
      uses: actions/setup-python@v3 # Использует действие setup-python для установки Python
      with:
        python-version: ${{ matrix.python-version }} # Указывает версию Python для установки
    - name: Install Dependencies # Название шага для установки зависимостей
      run: | # Запускает команды в командной строке
        python -m pip install --upgrade pip # Обновляет pip
        pip install -r requirements.txt # Устанавливает зависимости из файла requirements.txt
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests # Название шага для запуска тестов
      run: |
        python manage.py test # Запускает тесты Django
    - name: Start Service # Название шага для запуска Django сервера
      run: |
        python manage.py runserver # Запускает разработческий сервер Django
